# Generated by Django 4.2.7 on 2023-12-23 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wiki',
            options={'verbose_name': '博客', 'verbose_name_plural': '博客'},
        ),
    ]
