# Generated by Django 4.2.7 on 2023-12-23 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': '项目表', 'verbose_name_plural': '项目表'},
        ),
        migrations.AlterModelOptions(
            name='projectuser',
            options={'verbose_name': '项目参与者', 'verbose_name_plural': '项目参与者'},
        ),
    ]
