# Generated by Django 4.2.7 on 2023-12-23 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filerepository',
            options={'verbose_name': '文件库', 'verbose_name_plural': '文件库'},
        ),
    ]
